apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: cmFjY29vbi1hcGktdXNlcg==          # "raccoon-api-user" encoded
  DB_PASS: UmFjY29vbkFQSS11c2VyLXBhc3MteHl6  # "RaCcoonAPI-user-pass-xyz" encoded